import Head from "next/head";
import Nav from "../../../Components/Nav";
import Footer from "../../../Components/Footer";
import Hero from "../../../Components/Hero";
import styles from "../../../styles/Apply.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

export async function getServerSideProps({ locale }) {
    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ lang: locale, show_id: "FD" }),
    };
    const infoRes = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await infoRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
        },
    };
}

export default function Search(props) {
    const { t } = useTranslation();
    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>補件上傳水電配置圖說</h3>
                <div className={styles.checkForm}>
                    <h2>大會水電公司審核意見</h2>
                    <p className={styles.opinionBox}>未標示電箱位置</p>
                    <h2>請上傳水電配置圖</h2>
                    <div className={styles.upload}>
                        <label htmlFor="upload-photo">請選擇檔案上傳</label>
                        <input type="file" name="photo" id="upload-photo" />
                    </div>
                    <h2>或以下方工具繪製水電配置圖</h2>
                    <img src="/img/image7.png" />
                    <h2>水電配置圖範例</h2>
                    <div className={styles.write}>
                        <p>＃請標示鄰攤位及走道，方便識別攤位方位。</p>
                        <img src="/img/image21.png" />
                    </div>
                </div>
                <div className={styles.btns}>
                    <button className={styles.cancel}>取消</button>
                    <button className={styles.complete}>完成</button>
                </div>
            </Hero>
            <Footer />
        </div>
    );
}
