import Head from "next/head";
import Nav from "../../../Components/Nav";
import Footer from "../../../Components/Footer";
import Hero from "../../../Components/Hero";
import styles from "../../../styles/Apply.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

export async function getServerSideProps({ locale, query }) {
    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
            lang: locale,
            sid: "b481cb1bcb3f18baeb07562c6c7f915b28b804d09c90d0b495945f164eacca2a",
        }),
    };

    const infoRes = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await infoRes.json();

    options.body.append("application_form_id", `${query.id}`);

    const viewData = await fetch(
        `${process.env.API_BASE_URL}viewApply`,
        options
    ).then((response) => response.json());

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
            data: viewData,
        },
    };
}

export default function Check(props) {
    const { t } = useTranslation();
    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>{t("search.check")}</h3>
                <div className={styles.checkForm}>
                    <h2>{t("search.option")}</h2>
                    <p className={styles.opinionBox}>
                        {props.data.comment.hydro_comment}
                    </p>
                    <h2>{t("applyForm.stepOne.groupTwo.title")}</h2>
                    <div className={styles.formComplete}>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.companyName")}
                            </label>
                            <p>{props.data.proxy.proxy_company_name}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.taxID")}
                            </label>
                            <p>{props.data.proxy.proxy_tax_id}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.contactPerson")}
                            </label>
                            <p>{props.data.proxy.proxy_contact_person}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.phone")}
                            </label>
                            <p>{props.data.proxy.proxy_phone}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>E-mail</label>
                            <p>{props.data.proxy.proxy_email}</p>
                        </div>
                    </div>
                    <h2>{t("applyForm.stepOne.groupThree.title")}</h2>
                    <div className={styles.formCompleteInvoce}>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.companyName")}
                            </label>
                            <p>{props.data.invoice.invoice_comapny}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupTwo.taxID")}
                            </label>
                            <p>{props.data.invoice.invoice_taxid}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t(
                                    "applyForm.stepOne.groupThree.invoiceAddress"
                                )}
                            </label>
                            <p>{props.data.invoice.invoice_address}</p>
                        </div>
                        <div className={styles.formRow}>
                            <label>
                                {t("applyForm.stepOne.groupThree.remark")}：
                            </label>
                            <p>{props.data.invoice.remark}</p>
                        </div>
                    </div>
                    <h2>{t("applyForm.stepTwo.title")}</h2>
                    <div className={styles.applyItem}>
                        <table>
                            <thead>
                                <tr className={styles.title}>
                                    <th>
                                        {t("applyForm.preview.groupThree.no")}
                                    </th>
                                    <th>
                                        {t("applyForm.preview.groupThree.item")}
                                    </th>
                                    <th>
                                        {t(
                                            "applyForm.preview.groupThree.quantity"
                                        )}
                                    </th>
                                    <th>
                                        {t(
                                            "applyForm.preview.groupThree.unitPrice"
                                        )}
                                    </th>
                                    <th>
                                        {t(
                                            "applyForm.preview.groupThree.itemCost"
                                        )}
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className={styles.content}>
                                    <td>1</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>2</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>3</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>4</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.sum}>
                                    <td className={styles.sumTitle} colSpan={4}>
                                        {t(
                                            "applyForm.preview.groupThree.total"
                                        )}
                                    </td>
                                    <td>20,439</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <h2>{t("applyForm.preview.groupFour.title")}</h2>
                    <div className={styles.image}>
                        <p>
                            {t("applyForm.preview.groupFour.file")}{" "}
                            <span>JO318水電圖圖.jpg</span>
                        </p>
                        <img
                            src={process.env.imgKey + props.data.diagram_img}
                        />
                    </div>
                </div>
            </Hero>
            <Footer />
        </div>
    );
}
