import { useState } from "react";
import Head from "next/head";
import Nav from "../../../Components/Nav";
import Footer from "../../../Components/Footer";
import Hero from "../../../Components/Hero";
import styles from "../../../styles/Apply.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Popup from "../../../Components/Popup/Popup";
import SlideToggle from "react-slide-toggle";
import { StylesContext } from "@material-ui/styles";

export async function getServerSideProps({ locale }) {
    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ lang: locale, show_id: "FD" }),
    };
    const infoRes = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await infoRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
        },
    };
}

export default function Search(props) {
    const { t } = useTranslation();
    const [show, setShow] = useState(false);

    const close = () => {
        setShow(false);
    };

    const active = (e) => {
        if (e.target.checked) {
            e.target.parentNode.className = styles.checkedActive;
        } else {
            e.target.parentNode.className = "";
        }
    };
    const enableNextTextBox = (e) => {
        if (e.target.checked) {
            e.target.nextSibling.nextSibling.childNodes[1].removeAttribute(
                "disabled"
            );
            e.target.parentNode.className = styles.checkedActive;
        } else {
            e.target.nextSibling.nextSibling.childNodes[1].setAttribute(
                "disabled",
                ""
            );
            e.target.nextSibling.nextSibling.childNodes[1].value = null;
            e.target.parentNode.className = "";
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>水電申請修改</h3>
                <div className={styles.checkForm}>
                    <h2>大會水電公司審核意見</h2>
                    <p className={styles.opinionBox}></p>
                    <h2>代理或裝潢公司基本資料</h2>
                    <div className={styles.form}>
                        <div className={styles.formRow}>
                            <label>公司名稱</label>
                            <input
                                name="company"
                                type="text"
                                defaultValue={"丰彤設計有限公司"}
                            />
                        </div>
                        <div className={styles.formRow}>
                            <label>統一編號</label>
                            <input
                                name="uniformNum"
                                type="text"
                                defaultValue={"12653758"}
                            />
                        </div>
                        <div className={styles.formRow}>
                            <label>聯絡人</label>
                            <input
                                name="contactPerson"
                                type="text"
                                defaultValue={"張書源"}
                            />
                        </div>
                        <div className={styles.formRow}>
                            <label>電子郵件</label>
                            <input
                                name="email"
                                type="email"
                                defaultValue={"1fontal1999@gmail.com"}
                            />
                        </div>
                    </div>
                    <h2>開立發票資訊</h2>
                    <div className={styles.form}>
                        <div className={styles.formRow}>
                            <label>公司名稱</label>
                            <input
                                name="company"
                                type="text"
                                defaultValue={"尚立資訊有限公司"}
                            />
                        </div>
                        <div className={styles.formRow}>
                            <label>統一編號</label>
                            <input
                                name="uniformNum"
                                type="text"
                                defaultValue={"83465356"}
                            />
                        </div>
                        <div className={styles.formRow}>
                            <label>發票寄送地址</label>
                            <input
                                name="address"
                                type="text"
                                defaultValue={"台北市南京東路四段1號2樓"}
                            />
                        </div>
                        <div
                            className={[styles.formRow, styles.prepare].join(
                                " "
                            )}
                        >
                            <label htmlFor="prepare">備註</label>
                            <textarea defaultValue={"123"}></textarea>
                        </div>
                    </div>
                    <h2 className={styles.reviseTitle}>
                        水電追加申請項目
                        <button
                            className={styles.revise}
                            onClick={() => setShow(true)}
                        >
                            修改
                        </button>
                    </h2>
                    <div className={styles.applyItem}>
                        <table>
                            <thead>
                                <tr className={styles.title}>
                                    <th>項次</th>
                                    <th>申請項目</th>
                                    <th>數量</th>
                                    <th>單價</th>
                                    <th>複價</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className={styles.content}>
                                    <td>1</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>2</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>3</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.content}>
                                    <td>4</td>
                                    <td>
                                        用電110V電源箱 - 單相 110V 15A (1,500W)
                                    </td>
                                    <td>1</td>
                                    <td>1,950</td>
                                    <td>1,950</td>
                                </tr>
                                <tr className={styles.sum}>
                                    <td className={styles.sumTitle} colSpan={4}>
                                        合計總金額
                                    </td>
                                    <td>20,439</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                {show ? (
                    <Popup close={close}>
                        <div
                            className={styles.applyCheckBox}
                            onClick={(e) => {
                                // do not close modal if anything inside modal content is clicked
                                e.stopPropagation();
                            }}
                        >
                            <h2>水電追加申請項目</h2>
                            <div className={styles.group}>
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    Ａ.用電110V電源箱
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <p>
                                                        110V 用電計算說明：
                                                        0.5KW(千瓦)＝500W(瓦)＝5A(安培)；1KW(千瓦)＝1000W(瓦)＝10A(安培
                                                        (a)
                                                        110V攤位總用電量(KW)＝攤位上照明用電＋各種電器用品用電(電視、開飲機、電腦等)＋展示產品用電....總計。
                                                        (b)
                                                        110V免費累計電量(KW)＝參展攤位數
                                                        X 500W（每1攤位500W免費)
                                                        (c)
                                                        1100V需追申請之電量(KW)＝110V攤位總用電量扣除了110V免費累計電量；(a)
                                                        - (b) = (c) 。
                                                        請點選計算出的 (c) 值
                                                    </p>
                                                    <div
                                                        className={
                                                            styles.aGroup
                                                        }
                                                    >
                                                        <label htmlFor="500W">
                                                            <input
                                                                type="checkbox"
                                                                id="500W"
                                                                value="110V_5A"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            單 相 110V 5A
                                                            （500W）
                                                            <span>$ 650</span>
                                                        </label>
                                                        <label htmlFor="1000W">
                                                            <input
                                                                type="checkbox"
                                                                id="1000W"
                                                                value="110V_10A"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            單 相 110V
                                                            10A（1,000W）
                                                            <span>$ 1,300</span>
                                                        </label>
                                                        <label htmlFor="1500W">
                                                            <input
                                                                type="checkbox"
                                                                id="1500W"
                                                                value="110V_15A"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            單 相 110V
                                                            15A（1,500W）
                                                            <span>$ 1,950</span>
                                                        </label>
                                                        <label htmlFor="2KW">
                                                            <input
                                                                type="checkbox"
                                                                id="2KW"
                                                                value="110V/190V_2"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            三 相 110V/190V 2KW
                                                            <span>$ 2,600</span>
                                                        </label>
                                                        <label htmlFor="4KW">
                                                            <input
                                                                type="checkbox"
                                                                id="4KW"
                                                                value="110V/190V_4"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            三 相 110V/190V 4KW
                                                            <span>$ 5,200</span>
                                                        </label>
                                                        <label htmlFor="6KW">
                                                            <input
                                                                type="checkbox"
                                                                id="6KW"
                                                                value="110V/190V_6"
                                                                onChange={
                                                                    active
                                                                }
                                                            />
                                                            三 相 110V/190V 6KW
                                                            <span>$ 7,800</span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    B. 用電220V電源箱
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.bGroup
                                                        }
                                                    >
                                                        <label htmlFor="220V_15A">
                                                            <input
                                                                type="checkbox"
                                                                id="220V_15A"
                                                                value="220V_15A"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            三相 220V 動力用電
                                                            15A
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 2,994/組
                                                            </span>
                                                        </label>
                                                        <label htmlFor="220V_20A">
                                                            <input
                                                                type="checkbox"
                                                                id="220V_20A"
                                                                value="220V_20A"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            三相 220V 動力用電
                                                            20A
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 5,889/組
                                                            </span>
                                                        </label>
                                                        <label htmlFor="220V_30A">
                                                            <input
                                                                type="checkbox"
                                                                id="220V_30A"
                                                                value="220V_30A"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            三相 220V 動力用電
                                                            30A
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 7,834/組
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    C. 用電380V電源箱
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.bGroup
                                                        }
                                                    >
                                                        <label htmlFor="380V">
                                                            <input
                                                                type="checkbox"
                                                                id="380V"
                                                                value="380V"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            用電380V電源箱
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 2,994/組
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    D. 24小時用電
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.bGroup
                                                        }
                                                    >
                                                        <label htmlFor="electricity">
                                                            <input
                                                                type="checkbox"
                                                                id="electricity"
                                                                value="electricity"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            24小時用電
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 2,994/組
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    E. 給排水管
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.bGroup
                                                        }
                                                    >
                                                        <label htmlFor="drain_pipe">
                                                            <input
                                                                type="checkbox"
                                                                id="drain_pipe"
                                                                value="drain_pipe"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            給排水管
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 5,000 /組
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                                <SlideToggle
                                    duration={1000}
                                    collapsed={true}
                                    whenReversedUseBackwardEase={false}
                                    render={({
                                        toggle,
                                        setCollapsibleElement,
                                        toggleState,
                                    }) => (
                                        <div className={styles.card}>
                                            <div className="card-header">
                                                <label
                                                    className={[
                                                        styles.dropDown,
                                                        toggleState ===
                                                        "COLLAPSED"
                                                            ? styles.dropDown
                                                            : styles.active,
                                                    ].join(" ")}
                                                    onClick={toggle}
                                                >
                                                    F. 壓縮空氣
                                                    <span>
                                                        {toggleState ===
                                                            "EXPANDED" ||
                                                        toggleState ===
                                                            "EXPANDING" ? (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M1 9L8 2L15 9"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        ) : (
                                                            <svg
                                                                width="16"
                                                                height="10"
                                                                viewBox="0 0 16 10"
                                                                fill="none"
                                                                xmlns="http://www.w3.org/2000/svg"
                                                            >
                                                                <path
                                                                    d="M15 1L8 8L1 1"
                                                                    stroke="white"
                                                                    strokeWidth="2"
                                                                />
                                                            </svg>
                                                        )}
                                                    </span>
                                                </label>
                                            </div>
                                            <div
                                                className={styles.cardBody}
                                                ref={setCollapsibleElement}
                                            >
                                                <div
                                                    className={
                                                        styles.dropDownContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.bGroup
                                                        }
                                                    >
                                                        <label htmlFor="press_air">
                                                            <input
                                                                type="checkbox"
                                                                id="press_air"
                                                                value="press_air"
                                                                onChange={
                                                                    enableNextTextBox
                                                                }
                                                            />
                                                            壓縮空氣
                                                            <label
                                                                className={
                                                                    styles.num
                                                                }
                                                            >
                                                                數量
                                                                <input
                                                                    type="number"
                                                                    disabled
                                                                />
                                                            </label>
                                                            <span>
                                                                $ 2,994/組
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                />
                            </div>

                            <div className={styles.btns}>
                                <button
                                    className={styles.cancel}
                                    onClick={close}
                                >
                                    取消
                                </button>
                                <button className={styles.complete}>
                                    完成
                                </button>
                            </div>
                        </div>
                    </Popup>
                ) : null}
                <div className={styles.btns}>
                    <button className={styles.cancel}>取消</button>
                    <button className={styles.complete}>完成</button>
                </div>
            </Hero>
            <Footer />
        </div>
    );
}
