import { useState } from "react";
import Head from "next/head";
import Nav from "../Components/Nav";
import Footer from "../Components/Footer";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import FormCard from "../Components/Stepper/FormCard";
import Basic from "../Components/Forms/Basic";
import Choose from "../Components/Forms/Choose";
import Write from "../Components/Forms/Write";
import Preview from "../Components/Forms/Preview";

export async function getServerSideProps({ locale }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
        },
    };
}

export default function Apply(props) {
    const { t } = useTranslation();
    const [formStep, setFormStep] = useState(0);

    const nextFormStep = () => setFormStep((currentStep) => currentStep + 1);

    const prevFormStep = () => setFormStep((currentStep) => currentStep - 1);

    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero>
                <FormCard currentStep={formStep} prevFormStep={prevFormStep}>
                    {formStep >= 0 && (
                        <Basic
                            formStep={formStep}
                            nextFormStep={nextFormStep}
                        />
                    )}
                    {formStep >= 1 && (
                        <Choose
                            formStep={formStep}
                            nextFormStep={nextFormStep}
                        />
                    )}
                    {formStep >= 2 && (
                        <Write
                            formStep={formStep}
                            nextFormStep={nextFormStep}
                        />
                    )}

                    {formStep > 2 && <Preview />}
                </FormCard>
            </Hero>
            <Footer />
        </div>
    );
}
