import Head from "next/head";
import Nav from "../Components/Nav";
import Footer from "../Components/Footer";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Link from "next/link";
import { setCookie, getCookie } from "cookies-next";

export async function getServerSideProps({ locale, query, req, res }) {
    // console.log(getCookie("sid", { req, res }));
    // console.log(query.sid);
    let oldCookie = getCookie("sid", { req, res });
    if (query.sid !== undefined) {
        if (query.sid !== oldCookie) {
            setCookie("sid", query.sid, { req, res, maxAge: 60 * 6 * 24 });
        } else if (query.sid === getCookie("sid", { req, res })) {
            oldCookie = oldCookie;
        }
    } else if (query.sid === undefined || query.sid === "") {
        if (oldCookie !== undefined || oldCookie !== "") {
            oldCookie = oldCookie;
        }
        if (oldCookie === undefined) {
            return {
                redirect: {
                    destination:
                        "https://www.taiwantradeshows.com.tw/zh_TW/index.html",
                },
            };
        }
    }
    const form = new URLSearchParams();
    form.append("sid", getCookie("sid", { req, res }));

    const options = {
        method: "POST",
    };
    options.body = form;

    const sidData = await fetch(`${process.env.API_BASE_URL}sso`, options).then(
        (response) => response.json()
    );

    if (sidData.status === false) {
        return {
            redirect: {
                destination:
                    "https://www.taiwantradeshows.com.tw/zh_TW/index.html",
            },
        };
    }

    const optionsTwo = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
            lang: locale,
            event_uid: sidData.event_uid,
            company_id: sidData.company_id,
        }),
    };
    const infoData = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        optionsTwo
    ).then((response) => response.json());

    const applyRes = await fetch(
        `${process.env.API_BASE_URL}getApplyInfo`,
        optionsTwo
    );
    const applyInfo = await applyRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
            applyInfo: applyInfo,
            sidData: sidData,
        },
    };
}

export default function Home(props) {
    const { t } = useTranslation();

    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>{t("home.title")}</h3>
                <div
                    className={styles.homeContent}
                    dangerouslySetInnerHTML={{
                        __html: props.applyInfo.content,
                    }}
                ></div>
                <Link href={"/apply"}>
                    <a className={styles.homeApply}>{t("apply")}</a>
                </Link>
            </Hero>
            <Footer />
        </div>
    );
}
