import Head from "next/head";
import Nav from "../Components/Nav";
import Footer from "../Components/Footer";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Link from "next/link";

export async function getServerSideProps({ locale }) {
    const options = {
        method: "POST",
        headers: {
            cookie: "ci_session=tm7raoegfru3cidh8r88ljnovjura42a",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
            lang: locale,
            sid: "b481cb1bcb3f18baeb07562c6c7f915b28b804d09c90d0b495945f164eacca2a",
        }),
    };
    const res = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await res.json();

    const applyRes = await fetch(
        `${process.env.API_BASE_URL}getApplyInfo`,
        options
    );
    const applyInfo = await applyRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
            applyInfo: applyInfo,
        },
    };
}

export default function Home(props) {
    const { t } = useTranslation();

    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>{t("home.title")}</h3>
                <div
                    className={styles.homeContent}
                    dangerouslySetInnerHTML={{
                        __html: props.applyInfo.content,
                    }}
                ></div>
                <Link href={"/apply"}>
                    <a className={styles.homeApply}>{t("apply")}</a>
                </Link>
            </Hero>
            <Footer />
        </div>
    );
}
