import Head from "next/head";
import Nav from "../Components/Nav";
import Footer from "../Components/Footer";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { Link } from "@material-ui/core";

export async function getServerSideProps({ locale }) {
    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ lang: locale, show_id: "FD" }),
    };
    const infoRes = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await infoRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
        },
    };
}

export default function Search(props) {
    const { t } = useTranslation();
    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>申請查詢</h3>
                <div className={styles.applyItem}>
                    <table>
                        <thead>
                            <tr className={styles.title}>
                                <th>項次</th>
                                <th>申請單號</th>
                                <th>日期</th>
                                <th>申請狀態</th>
                                <th>配置圖狀態</th>
                                <th>繳款單</th>
                                <th>繳費證明</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr className={styles.content}>
                                <td>1</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>審核通過</td>
                                <td className={styles.state}>已確認</td>
                                <td className={styles.download}>下載</td>
                                <td className={styles.upload}>
                                    <label htmlFor="upload">上傳</label>
                                    <input
                                        type="file"
                                        name="photo"
                                        id="upload"
                                    />
                                </td>
                                <td>
                                    <Link
                                        href={`/apply/check/${1}`}
                                        className={styles.delete}
                                    >
                                        <a>檢示</a>
                                    </Link>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>2</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>通知修改</td>
                                <td className={styles.state}>
                                    未上傳
                                    <Link
                                        href={`/apply/insufficient/${1}`}
                                        className={styles.documents}
                                    >
                                        <a>補件</a>
                                    </Link>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    <Link href={`/apply/revise/${1}`}>
                                        <a>修改</a>
                                    </Link>
                                    <span>取消</span>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>3</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>通知修改</td>
                                <td className={styles.state}>
                                    通知補件
                                    <Link
                                        href={`/apply/insufficient/${1}`}
                                        className={styles.documents}
                                    >
                                        <a>補件</a>
                                    </Link>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    <Link href={`/apply/revise/${1}`}>
                                        <a>修改</a>
                                    </Link>
                                    <span>取消</span>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>4</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>審核通過</td>
                                <td className={styles.state}>
                                    通知補件
                                    <Link
                                        href={`/apply/insufficient/${1}`}
                                        className={styles.documents}
                                    >
                                        <a>補件</a>
                                    </Link>
                                </td>
                                <td className={styles.download}>下載</td>
                                <td className={styles.upload}>
                                    <label htmlFor="upload2">上傳</label>
                                    <input
                                        type="file"
                                        name="photo"
                                        id="upload2"
                                    />
                                </td>
                                <td>
                                    <Link
                                        href={`/apply/check/${1}`}
                                        className={styles.delete}
                                    >
                                        <a>檢示</a>
                                    </Link>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>5</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>待審核</td>
                                <td className={styles.state}>
                                    待確認
                                    <Link
                                        href={`/apply/insufficient/${1}`}
                                        className={styles.documents}
                                    >
                                        <a>補件</a>
                                    </Link>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    <Link href={`/apply/revise/${1}`}>
                                        <a>修改</a>
                                    </Link>
                                    <span>取消</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </Hero>
            <Footer />
        </div>
    );
}
