import Head from "next/head";
import Nav from "../Components/Nav";
import Footer from "../Components/Footer";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

export async function getServerSideProps({ locale }) {
    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ lang: locale, show_id: "FD" }),
    };
    const infoRes = await fetch(
        `${process.env.API_BASE_URL}getDiscountInfo`,
        options
    );
    const infoData = await infoRes.json();

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"])),
            info: infoData,
        },
    };
}

export default function Search(props) {
    const { t } = useTranslation();
    return (
        <div className={styles.container}>
            <Head>
                <title>TAITRA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/img/logo.svg" />
                {/* <link
                    href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700;900&display=swap"
                    rel="stylesheet"
                /> */}
            </Head>

            <Nav />
            <Hero info={props.info}>
                <h3>申請查詢</h3>
                <div className={styles.applyItem}>
                    <table>
                        <thead>
                            <tr className={styles.title}>
                                <th>項次</th>
                                <th>申請單號</th>
                                <th>日期</th>
                                <th>申請狀態</th>
                                <th>配置圖狀態</th>
                                <th>繳款單</th>
                                <th>繳費證明</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr className={styles.content}>
                                <td>1</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>審核通過</td>
                                <td className={styles.state}>已確認</td>
                                <td className={styles.download}>下載</td>
                                <td className={styles.upload}>上傳</td>
                                <td className={styles.delete}>檢示</td>
                            </tr>
                            <tr className={styles.content}>
                                <td>2</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>通知修改</td>
                                <td className={styles.state}>
                                    未上傳
                                    <span className={styles.documents}>
                                        補件
                                    </span>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    修改<span>取消</span>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>3</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>通知修改</td>
                                <td className={styles.state}>
                                    通知補件
                                    <span className={styles.documents}>
                                        補件
                                    </span>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    修改<span>取消</span>
                                </td>
                            </tr>
                            <tr className={styles.content}>
                                <td>4</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>審核通過</td>
                                <td className={styles.state}>
                                    通知補件
                                    <span className={styles.documents}>
                                        補件
                                    </span>
                                </td>
                                <td className={styles.download}>下載</td>
                                <td className={styles.upload}>上傳</td>
                                <td className={styles.delete}>檢示</td>
                            </tr>
                            <tr className={styles.content}>
                                <td>5</td>
                                <td>EW-FD20220001</td>
                                <td>2022-04-05</td>
                                <td>待審核</td>
                                <td className={styles.state}>
                                    待確認
                                    <span className={styles.documents}>
                                        補件
                                    </span>
                                </td>
                                <td></td>
                                <td></td>
                                <td className={styles.delete}>
                                    修改<span>取消</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </Hero>
            <Footer />
        </div>
    );
}
